### ISSUE TITLE
‼️ Error when running truffle migrate

### ISSUE THREAD

**Issue by Gizmotronn** [Signal-Kinetics/nft-game#1]
Console error:
```
…/nft-game on 🌱 master [✘!?] via 🤖 v16.0.0 took 6s 
❯ truffle migrate --network development --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xfe1e0fc3cf4acc09981e51a7a75599060b98ea1b2a72ecd11b9fb5bfba56ce6a
   > Blocks: 0            Seconds: 0
   > contract address:    0xb2E1Ec5d329422e8E18f55E24FD5Ab573dDd2334
   > block number:        11
   > block timestamp:     1624717531
   > account:             0x19d1cd118724DeD9FEC72f46c3d46D5C7e2a99fA
   > balance:             99.6618212
   > gas used:            244300 (0x3ba4c)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.004886 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:            0.004886 ETH


2_token_migration.js
====================

   Deploying 'Token'
   -----------------
   > transaction hash:    0xfa926c302f3a529415e1db3d198f2b53ab86f11f01c2e3cd831cad1d649b8355
   > Blocks: 0            Seconds: 0
   > contract address:    0x5B622a118Bb5Ba64Df45A165b7edc68f73DEeEed
   > block number:        13
   > block timestamp:     1624717532
   > account:             0x19d1cd118724DeD9FEC72f46c3d46D5C7e2a99fA
   > balance:             99.60716676
   > gas used:            2690209 (0x290ca1)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.05380418 ETH


Error: Token has not been deployed to detected network (network/artifact mismatch)
    at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:245:1)
    at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:83:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at module.exports (/Users/liam/Documents/Webapps/KeybaseRepos/nft-game/migrations/2_token_migration.js:5:25)
Truffle v5.3.12 (core: 5.3.12)
Node v16.0.0
UnhandledRejections detected
Promise {
  <rejected> Error: Token has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:245:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:83:1)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at module.exports (/Users/liam/Documents/Webapps/KeybaseRepos/nft-game/migrations/2_token_migration.js:5:25)
} Error: Token has not been deployed to detected network (network/artifact mismatch)
    at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:245:1)
    at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:83:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at module.exports (/Users/liam/Documents/Webapps/KeybaseRepos/nft-game/migrations/2_token_migration.js:5:25)
(base) 
```

**Comment by Gizmotronn** [comment]
https://forum.moralis.io/t/truffle-migrate-error-token-has-not-been-deployed-to-detected-network-from-tutorial-nft-game-in-12-hours/953

**Comment by rishistyping** [comment]
@EXYNOS-999 Assign.

**Comment by Gizmotronn** [comment]
> @EXYNOS-999 Assign.

Cheers
